### ISSUE TITLE
Too long to understand

### ISSUE THREAD

**Issue by pdumin** [vkadnikov92/NewsBuddy#1]
https://github.com/vkadnikov92/NewsBuddy/blob/519fdb12c40dc97d194f563ffed768144918d46c/models/news_to_cloud.py#L94

**Comment by Rzhischev** [comment]
На самом деле это из-за особенностей MyStem:
'gr' — это ключ, который содержит грамматическую информацию о слове.
'S' — это обозначение существительного.
word['analysis'] - это часть словаря word, которая содержит анализ данного слова. 
ключ 'lex' в словаре  представляет наиболее вероятную интерпретацию слова. 

Согласен, что сложно понять, но таков MyStem
