### ISSUE TITLE
Не используется нигде ниже

### ISSUE THREAD

**Issue by pdumin** [vkadnikov92/NewsBuddy#2]
https://github.com/vkadnikov92/NewsBuddy/blob/519fdb12c40dc97d194f563ffed768144918d46c/bot.py#L1C8-L1C10

**Comment by Rzhischev** [comment]
Это для передачи чувствительных данных в окружение. Когда создаём докер образ, то отказываемся от файла конфигурации и передаём данные в окружение при запуске bot.py
